spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: vende-mais-back

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

vende:
  mais:
    integration:
      random:
        user:
          api:
            url: ${RANDOM_USER_API_URL:https://randomuser.me}
            path: ${RANDOM_USER_API_PATH:/api/}